/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplyRouteRouteImport } from './routes/apply.route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedRequisitionsRouteImport } from './routes/_authenticated/requisitions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as ApplyOrgIdRouteImport } from './routes/apply.$orgId'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as CandidateAuthRouteImport } from './routes/candidate.auth'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates.index'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as ApplyPositionIdRouteImport } from './routes/apply.position.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRouteRoute = ApplyRouteRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequisitionsRoute =
  AuthenticatedRequisitionsRouteImport.update({
    id: '/requisitions',
    path: '/requisitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const ApplyOrgIdRoute = ApplyOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAuthRoute = CandidateAuthRouteImport.update({
  id: '/candidate/auth',
  path: '/candidate/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApplyPositionIdRoute = ApplyPositionIdRouteImport.update({
  id: '/position/$id',
  path: '/position/$id',
  getParentRoute: () => ApplyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/requisitions': typeof AuthenticatedRequisitionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/apply/$orgId': typeof ApplyOrgIdRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/apply/': typeof ApplyIndexRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/apply/position/$id': typeof ApplyPositionIdRoute
  '/candidates/': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/requisitions': typeof AuthenticatedRequisitionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/apply/$orgId': typeof ApplyOrgIdRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/apply': typeof ApplyIndexRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/apply/position/$id': typeof ApplyPositionIdRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/requisitions': typeof AuthenticatedRequisitionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/apply/$orgId': typeof ApplyOrgIdRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/auth': typeof CandidateAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/apply/': typeof ApplyIndexRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/apply/position/$id': typeof ApplyPositionIdRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/docs'
    | '/onboarding'
    | '/sitemap.xml'
    | '/analytics'
    | '/export'
    | '/import'
    | '/pipeline'
    | '/requisitions'
    | '/settings'
    | '/workspace'
    | '/apply/$orgId'
    | '/candidate/applications'
    | '/candidate/auth'
    | '/invite/$token'
    | '/apply/'
    | '/candidates/$id'
    | '/apply/position/$id'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/onboarding'
    | '/sitemap.xml'
    | '/analytics'
    | '/export'
    | '/import'
    | '/pipeline'
    | '/requisitions'
    | '/settings'
    | '/workspace'
    | '/apply/$orgId'
    | '/candidate/applications'
    | '/candidate/auth'
    | '/invite/$token'
    | '/apply'
    | '/candidates/$id'
    | '/apply/position/$id'
    | '/candidates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/docs'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/export'
    | '/_authenticated/import'
    | '/_authenticated/pipeline'
    | '/_authenticated/requisitions'
    | '/_authenticated/settings'
    | '/_authenticated/workspace'
    | '/apply/$orgId'
    | '/candidate/applications'
    | '/candidate/auth'
    | '/invite/$token'
    | '/apply/'
    | '/_authenticated/candidates/$id'
    | '/apply/position/$id'
    | '/_authenticated/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRouteRoute: typeof ApplyRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateAuthRoute: typeof CandidateAuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requisitions': {
      id: '/_authenticated/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof AuthenticatedRequisitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/apply/$orgId': {
      id: '/apply/$orgId'
      path: '/$orgId'
      fullPath: '/apply/$orgId'
      preLoaderRoute: typeof ApplyOrgIdRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/auth': {
      id: '/candidate/auth'
      path: '/candidate/auth'
      fullPath: '/candidate/auth'
      preLoaderRoute: typeof CandidateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apply/position/$id': {
      id: '/apply/position/$id'
      path: '/position/$id'
      fullPath: '/apply/position/$id'
      preLoaderRoute: typeof ApplyPositionIdRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedRequisitionsRoute: typeof AuthenticatedRequisitionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedRequisitionsRoute: AuthenticatedRequisitionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApplyRouteRouteChildren {
  ApplyOrgIdRoute: typeof ApplyOrgIdRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApplyPositionIdRoute: typeof ApplyPositionIdRoute
}

const ApplyRouteRouteChildren: ApplyRouteRouteChildren = {
  ApplyOrgIdRoute: ApplyOrgIdRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  ApplyPositionIdRoute: ApplyPositionIdRoute,
}

const ApplyRouteRouteWithChildren = ApplyRouteRoute._addFileChildren(
  ApplyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRouteRoute: ApplyRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateAuthRoute: CandidateAuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
